### ISSUE TITLE
Unable to publish the APK

### ISSUE THREAD

**Issue by ganeshvl** [jenkinsci/fabric-beta-publisher-plugin#45] opened 2019-02-14 05:49 UTC
Hi,

Can you please look into this error log and let me know the probable cause for this issue.
1. I'm trying to publish the apk into BETA from the Jenkins CI
2. This is running under proxy.  

12:47:55 ERROR: Step ‘Upload .apk to Fabric Beta’ aborted due to exception: 
12:47:55 java.net.SocketTimeoutException: connect timed out
12:47:55 	at java.net.PlainSocketImpl.socketConnect(Native Method)
12:47:55 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
12:47:55 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
12:47:55 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
12:47:55 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
12:47:55 	at java.net.Socket.connect(Socket.java:589)
12:47:55 	at okhttp3.internal.Platform.connectSocket(Platform.java:121)
12:47:55 	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:185)
12:47:55 	at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:170)
12:47:55 	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
12:47:55 	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
12:47:55 	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
12:47:55 	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
12:47:55 	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
12:47:55 	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
12:47:55 	at okhttp3.RealCall.getResponse(RealCall.java:243)
12:47:55 	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
12:47:55 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
12:47:55 	at okhttp3.RealCall.execute(RealCall.java:57)
12:47:55 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
12:47:55 	at fabric.beta.publisher.FileUtils.downloadCrashlyticsTools(FileUtils.java:31)
12:47:55 	at fabric.beta.publisher.FabricBetaPublisher.prepareCrashlytics(FabricBetaPublisher.java:191)
12:47:55 	at fabric.beta.publisher.FabricBetaPublisher.publishFabric(FabricBetaPublisher.java:116)
12:47:55 	at fabric.beta.publisher.FabricBetaPublisher.perform(FabricBetaPublisher.java:87)
12:47:55 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
12:47:55 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
12:47:55 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
12:47:55 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
12:47:55 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
12:47:55 	at hudson.model.Run.execute(Run.java:1835)
12:47:55 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:47:55 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:47:55 	at hudson.model.Executor.run(Executor.java:429)

**Comment by egor-n** [comment] 2019-02-14 09:25
Duplicate of #41

**Closed by egor-n** 2019-02-14 09:25 UTC
Labels: duplicate

**Comment by waylon-edmodo** [comment] 2019-10-09 02:43
Fabric Beta Publisher Plugin:
Error downloading crashlytics-devtools.jar: timeout
Temporary xml2704367587277803670.tmp got deleted = true
Build step 'Upload .apk to Fabric Beta' marked build as failure
Finished: FAILURE
