### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sairajkishore** [jenkinsci/fabric-beta-publisher-plugin#38] opened 2018-10-15 09:34 UTC
Hi below is the error, when iam trying to uplaod my apk to fabric from jenkins through plugin.
only difference is i have different flavours in fabric.

Building in workspace /Users/home/.jenkins/workspace/Android1
Fabric Beta Publisher Plugin:
Temporary crashlytics5770930698323578486.zip got deleted = true
ERROR: Build step failed with exception
java.lang.ArrayIndexOutOfBoundsException
Build step 'Upload .apk to Fabric Beta' marked build as failure

**Comment by egor-n** [comment] 2018-11-24 17:08
Duplicate of #32.

**Closed by egor-n** 2018-11-24 17:08 UTC
Labels: duplicate
